name: garner
version: 0.1.0.0
github: "garnix-io/garner"
license: AllRightsReserved
author: "garnix"
maintainer: "contact@garnix.io"
copyright: "AllRightsReserved"

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FunctionalDependencies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedLabels
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ScopedTypeVariables
  - StandaloneDeriving

dependencies:
  - base >= 4.7 && < 5
  - shake
  - getopt-generics
  - interpolate

ghc-options:
  - -Wall
  - -with-rtsopts=-T

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test/spec
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-discover
      - mockery
      - silently
      - directory

library:
  source-dirs:
    - src

executables:
  garner:
    main: exe/garner.hs
    dependencies:
      - garner
